### PR TITLE
all: revert some changes, merge upstream into our fork

### PR DESCRIPTION
**Pull request by josharian**
This is going to suck to review. I'm sorry.

I humbly recommend:

* Looking commit by commit at the reverts I made. I'm mainly interested in confirmation that it is safe to revert the commit. The opinions of @danderson and @crawshaw would be particularly useful here. A review of the code changes is also welcome, but less pressing.

* Not attempting to review the merge. It took me almost eight hours of painstaking work, and comparing of diffs, I'm pretty sure it's right. Instead, I suggest looking at a diff vs upstream afterwards. I will paste said diff here shortly for your convenience.

I will send a PR to tailscale/tailscale shortly that adjusts to this newly merged version.

### CODE REVIEW

**Comment by josharian** [comment]
Sigh. GitHub decided to display ALL the new commits (including those merged from upstream). The reverts worth reviewing are everthing at the bottom of its list, after `main: add back version file`.

**Review by danderson — COMMENTED** [review]
The reverts LGTM. I assumed (correctly, it seems) that everything else is the things pulled from upstream.

I have not yet reviewed the diff w/ upstream, but will do that as soon as you post it.

**Comment by josharian** [comment]
Here is most of `git diff u/master josh/revert-then-merge`. I have omitted:

* `.github/workflows/` (all additions, no merge conflicts, only on our fork, will be deleted later)
* `.gitignore`, `README.md` (doesn't matter much, nothing interesting)
* import path changes

```diff
diff --git a/device/device.go b/device/device.go
@@ -25,6 +24,11 @@ type Device struct {
 	isClosed AtomicBool // device is closed? (acting as guard)
 	log      *Logger
 
+	handshakeDone  func(peerKey NoisePublicKey, peer *Peer, allowedIPs *AllowedIPs)
+	skipBindUpdate bool
+	createBind     func(uport uint16, device *Device) (conn.Bind, uint16, error)
+	createEndpoint func(key [32]byte, s string) (conn.Endpoint, error)
+
 	// synchronized resources (locks acquired in order)
 
 	state struct {
@@ -273,8 +277,11 @@ func (device *Device) SetPrivateKey(sk NoisePrivateKey) error {
 	}
 
 	// remove peers with matching public keys
+	var publicKey NoisePublicKey // allow a zero key here for disabling this device
+	if !sk.IsZero() {
+		publicKey = sk.publicKey()
+	}
 
-	publicKey := sk.publicKey()
 	for key, peer := range device.peers.keyMap {
 		if peer.handshake.remoteStatic.Equals(publicKey) {
 			peer.handshake.mutex.RUnlock()
@@ -308,10 +315,48 @@ func (device *Device) SetPrivateKey(sk NoisePrivateKey) error {
 	return nil
 }
 
-func NewDevice(tunDevice tun.Device, logger *Logger) *Device {
+type DeviceOptions struct {
+	Logger *Logger
+
+	// HandshakeDone is called every time we complete a peer handshake.
+	HandshakeDone func(peerKey NoisePublicKey, peer *Peer, allowedIPs *AllowedIPs)
+
+	CreateEndpoint func(key [32]byte, s string) (conn.Endpoint, error)
+	CreateBind     func(uport uint16) (conn.Bind, uint16, error)
+	SkipBindUpdate bool // if true, CreateBind only ever called once
+}
+
+func NewDevice(tunDevice tun.Device, opts *DeviceOptions) *Device {
 	device := new(Device)
 	device.closed = make(chan struct{})
-	device.log = logger
+
+	device.isUp.Set(false)
+	device.isClosed.Set(false)
+
+	if opts != nil {
+		if opts.Logger != nil {
+			device.log = opts.Logger
+		}
+		device.handshakeDone = opts.HandshakeDone
+		if opts.CreateEndpoint != nil {
+			device.createEndpoint = opts.CreateEndpoint
+		} else {
+			device.createEndpoint = func(_ [32]byte, s string) (conn.Endpoint, error) {
+				return conn.CreateEndpoint(s)
+			}
+		}
+		if opts.CreateBind != nil {
+			device.createBind = func(uport uint16, device *Device) (conn.Bind, uint16, error) {
+				return opts.CreateBind(uport)
+			}
+		} else {
+			device.createBind = func(uport uint16, device *Device) (conn.Bind, uint16, error) {
+				return conn.CreateBind(uport)
+			}
+		}
+		device.skipBindUpdate = opts.SkipBindUpdate
+	}
+
 	device.tun.device = tunDevice
 	mtu, err := device.tun.device.MTU()
 	if err != nil {
@@ -497,6 +542,11 @@ func (device *Device) BindUpdate() error {
 	device.net.Lock()
 	defer device.net.Unlock()
 
+	if device.skipBindUpdate && device.net.bind != nil {
+		device.log.Verbosef("UDP bind update skipped")
+		return nil
+	}
+
 	// close existing sockets
 
 	if err := unsafeCloseBind(device); err != nil {
@@ -511,7 +561,7 @@ func (device *Device) BindUpdate() error {
 
 		var err error
 		netc := &device.net
-		netc.bind, netc.port, err = conn.CreateBind(netc.port)
+		netc.bind, netc.port, err = device.createBind(netc.port, device)
 		if err != nil {
 			netc.bind = nil
 			netc.port = 0
diff --git a/device/device_test.go b/device/device_test.go
index 50e3dbc5a..5c254f915 100644
--- a/device/device_test.go
+++ b/device/device_test.go
@@ -155,7 +155,9 @@ NextAttempt:
 			if _, ok := tb.(*testing.B); ok && !testing.Verbose() {
 				level = LogLevelError
 			}
-			p.dev = NewDevice(p.tun.TUN(), NewLogger(level, fmt.Sprintf("dev%d: ", i)))
+			p.dev = NewDevice(p.tun.TUN(), &DeviceOptions{
+				Logger: NewLogger(level, fmt.Sprintf("dev%d: ", i)),
+			})
 			p.dev.Up()
 			if err := p.dev.IpcSet(cfg[i]); err != nil {
 				// genConfigs attempted to pick ports that were free.
@@ -317,7 +319,9 @@ func randDevice(t *testing.T) *Device {
 	}
 	tun := newDummyTUN("dummy")
 	logger := NewLogger(LogLevelError, "")
-	device := NewDevice(tun, logger)
+	device := NewDevice(tun, &DeviceOptions{
+		Logger: logger,
+	})
 	device.SetPrivateKey(sk)
 	return device
 }
diff --git a/device/queueconstants_ios.go b/device/queueconstants_ios.go
index be30e1963..a38ae2280 100644
--- a/device/queueconstants_ios.go
+++ b/device/queueconstants_ios.go
@@ -10,10 +10,10 @@ package device
 /* Fit within memory limits for iOS's Network Extension API, which has stricter requirements */
 
 const (
-	QueueStagedSize            = 128
-	QueueOutboundSize          = 1024
-	QueueInboundSize           = 1024
-	QueueHandshakeSize         = 1024
+	QueueStagedSize            = 64
+	QueueOutboundSize          = 64
+	QueueInboundSize           = 64
+	QueueHandshakeSize         = 64
 	MaxSegmentSize             = 1700
-	PreallocatedBuffersPerPool = 1024
+	PreallocatedBuffersPerPool = 64
 )
diff --git a/device/uapi.go b/device/uapi.go
@@ -47,9 +46,19 @@ var byteBufferPool = &sync.Pool{
 	New: func() interface{} { return new(bytes.Buffer) },
 }
 
+// IPCGetFilter are options to control which fields are omitted from Device.IpcGetOperationFiltered.
+type IPCGetFilter struct {
+	// FilterAllowedIPs controls whether AllowedIPs are omitted in the output.
+	FilterAllowedIPs bool
+}
+
+func (device *Device) IpcGetOperation(w io.Writer) error {
+	return device.IpcGetOperationFiltered(w, IPCGetFilter{})
+}
+
 // IpcGetOperation implements the WireGuard configuration protocol "get" operation.
 // See https://www.wireguard.com/xplatform/#configuration-protocol for details.
-func (device *Device) IpcGetOperation(w io.Writer) error {
+func (device *Device) IpcGetOperationFiltered(w io.Writer, filter IPCGetFilter) error {
 	device.ipcMutex.RLock()
 	defer device.ipcMutex.RUnlock()
 
@@ -122,10 +131,12 @@ func (device *Device) IpcGetOperation(w io.Writer) error {
 			sendf("rx_bytes=%d", atomic.LoadUint64(&peer.stats.rxBytes))
 			sendf("persistent_keepalive_interval=%d", atomic.LoadUint32(&peer.persistentKeepaliveInterval))
 
-			device.allowedips.EntriesForPeer(peer, func(ip net.IP, cidr uint) bool {
-				sendf("allowed_ip=%s/%d", ip.String(), cidr)
-				return true
-			})
+			if !filter.FilterAllowedIPs {
+				device.allowedips.EntriesForPeer(peer, func(ip net.IP, cidr uint) bool {
+					sendf("allowed_ip=%s/%d", ip.String(), cidr)
+					return true
+				})
+			}
 		}
 	}()
 
@@ -331,7 +342,10 @@ func (device *Device) handlePeerLine(peer *ipcSetPeer, key, value string) error
 
 	case "endpoint":
 		device.log.Verbosef("%v - UAPI: Updating endpoint", peer.Peer)
-		endpoint, err := conn.CreateEndpoint(value)
+		peer.handshake.mutex.Lock()
+		key := peer.handshake.remoteStatic
+		peer.handshake.mutex.Unlock()
+		endpoint, err := device.createEndpoint(key, value)
 		if err != nil {
 			return ipcErrorf(ipc.IpcErrorInvalid, "failed to set endpoint %v: %w", value, err)
 		}
diff --git a/main.go b/main.go
@@ -219,7 +219,9 @@ func main() {
 		return
 	}
 
-	device := device.NewDevice(tun, logger)
+	device := device.NewDevice(tun, &device.DeviceOptions{
+		Logger: logger,
+	})
 
 	logger.Verbosef("Device started")
 
diff --git a/main_windows.go b/main_windows.go
@@ -47,7 +47,9 @@ func main() {
 		os.Exit(ExitSetupFailed)
 	}
 
-	device := device.NewDevice(tun, logger)
+	device := device.NewDevice(tun, &device.DeviceOptions{
+		Logger: logger,
+	})
 	device.Up()
 	logger.Verbosef("Device started")
 ```

**Comment by josharian** [comment]
Companion oss pr: https://github.com/tailscale/tailscale/pull/1269

**Review by danderson — APPROVED** [review]

**Comment by danderson** [comment]
Reviewed in pairing, LGTM

**Comment by crawshaw** [comment]
The diff to upstream certainly LGTM. I haven't gone through the reverted commits yet, but if @danderson is happy with them I think that's enough sign-off.

**Comment by josharian** [comment]
Great, thanks for looking. The diff is getting small!

**Pull request merged**
