### PR TITLE
.github/workflows: run tests on Linux and Windows

### PR DESCRIPTION
**Pull request by alexbrainman**
This change adds Github Actions to run tests on Linux and Windows.
Both normal and race-enabled tests.

Fixes tailscale/tailscale#913

Signed-off-by: Alex Brainman <alex.brainman@gmail.com>

### CODE REVIEW

**Comment by alexbrainman** [comment]
@josharian 

Brad suggested I send this change for you to review (see https://github.com/tailscale/tailscale/issues/913#issuecomment-738922664).

I tested it works on both Linux and Windows. I do not know why Github Actions did not run on my PR creation. Perhaps you need to enable Github Actions somewhere in this repo settings.

Thank you.

Alex

**Comment by josharian** [comment]
Thanks, Alex. Before I review the details of this PR, I'd like to hear from @zx2c4 about the idea of adding GitHub CI support, since I believe he prefers to receive contributions via other means, and this repo is intended to be just a mirror.

**Comment by alexbrainman** [comment]
> Before I review the details of this PR, I'd like to hear from @zx2c4 about the idea of adding GitHub CI support, since I believe he prefers to receive contributions via other means, and this repo is intended to be just a mirror.

The reason I decided to add Github Actions here is that I discovered some tests failed https://github.com/tailscale/tailscale/issues/913. I am fine with whatever you and Jason decide, I just don't see any harm in running tests on every commit in this repo.

Alex

**Comment by zx2c4** [comment]
We generally don't use github for infra upstream, unless a repository maintainer prefers it. But this PR concerns your fork which you keep developing apparently, so not sure what to say here, except that I wish this energy would be placed into upstream development instead of your fork.

**Comment by alexbrainman** [comment]
> except that I wish this energy would be placed into upstream development instead of your fork.

I will let @josharian answer that. But since this fork already exists, we should make sure all code builds. Therefore my PR.

I am OK to drop this PR if it creates some problems. But I don't see what problems it creates.

Alex

**Comment by josharian** [comment]
I'm sorry. I missed that this PR was for the Tailscale fork. We do want to eliminate this fork, but as we work towards that, I see no reason not have have CI. I'll review this when I'm back at my desk.

**Comment by bradfitz** [comment]
@zx2c4, to echo what @josharian said: we do not want a fork long-term. Forks are annoying and a lot of work. We celebrate when we delete our forks (as we have a few times now). We're working on getting there with Wireguard.

**Comment by josharian** [comment]
This would be useful as I wrap up de-fork-ing. This PR is out of date, but I'm going to re-create in a new PR.

**Comment by alexbrainman** [comment]
> his would be useful as I wrap up de-fork-ing. This PR is out of date, but I'm going to re-create in a new PR.

Sounds good. I can see your PR https://github.com/tailscale/wireguard-go/pull/32

Alex

**Pull request closed without merging**
