### PR TITLE
device: close queues when we are done with them

### PR DESCRIPTION
**Pull request by josharian**
This change is [Reviewable](https://reviewable.io/reviews/tailscale/wireguard-go/21)

### CODE REVIEW

**Comment by josharian** [comment]
My benchmarking is super noisy, but this appears to speed up pinging a la TestTwoDevicePing by 5-7%.

**Comment by josharian** [comment]
Please do not review yet.

**Comment by crawshaw** [comment]
FYI: you can move a PR into draft mode to signal do-not-review

**Comment by josharian** [comment]
Oh brave new GitHub world that has such features in it.

**Pull request closed without merging**
